version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - NODE_ENV=production
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  backend:
    build: .
    container_name: backend_container
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
