version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - NODE_ENV=production
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  back:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
